Update le Dockerfile et application.properties

diff --git a/.github/actions/publish-api-image/action.yml b/.github/actions/publish-api-image/action.yml
--- a/.github/actions/publish-api-image/action.yml
+++ b/.github/actions/publish-api-image/action.yml
@@ -31,26 +31,40 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: Debug IMAGENAME
+    - name: Debug Input Values
+      run: |
+        echo "ECR Registry: ${{ inputs.ecr-registry }}"
+        echo "Image Prefix: ${{ inputs.image-prefix }}"
+        echo "Image Short Name: ${{ inputs.image-short-name }}"
+        echo "Image Tag: ${{ inputs.image-tag }}"
+      shell: bash
+
+    - name: Define and Debug IMAGENAME
       run: |
         # Define the image name correctly
-        export IMAGENAME="${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}"
+        export IMAGENAME="${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}:${{ inputs.image-tag }}"
         echo "Generated IMAGENAME: $IMAGENAME"
+        
+        # Verifier que IMAGENAME est correctement formé
+        if [ -z "$IMAGENAME" ]; then
+          echo "IMAGENAME is empty or invalid. Exiting..."
+          exit 1
+        fi
       shell: bash
 
     - name: Build and Push Docker Image
       run: |
-        # Débogage : afficher le nom de l'image
+        # Afficher IMAGENAME pour le débogage
         echo "IMAGENAME: $IMAGENAME"
 
         # Build the Docker image
-        docker build --build-arg SPRING_PROFILE_ARG=${{ inputs.spring-profile }} -f ${{ inputs.dockerfile }} -t $IMAGENAME:${{ inputs.image-tag }} .
+        docker build --build-arg SPRING_PROFILE_ARG=${{ inputs.spring-profile }} -f ${{ inputs.dockerfile }} -t $IMAGENAME .
 
         # Tag and push the Docker image
-        docker image tag $IMAGENAME:${{ inputs.image-tag }} $IMAGENAME:latest
-        docker push $IMAGENAME:${{ inputs.image-tag }}
+        docker tag $IMAGENAME $IMAGENAME:latest
+        docker push $IMAGENAME
         docker push $IMAGENAME:latest
 
         # Output the image URI
-        echo "image-uri=${IMAGENAME}:latest" >> $GITHUB_ENV
+        echo "image-uri=${IMAGENAME}" >> $GITHUB_ENV
       shell: bash
